"""baseline schema — all tables from models

Baseline migration for adopting Alembic on the existing model set. It builds
the schema from `Base.metadata` (guaranteed consistent with the ORM). Every
change AFTER this should be a normal autogenerated revision:

    alembic revision --autogenerate -m "add X"

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-12
"""
from typing import Sequence, Union

from alembic import op

from app import models  # noqa: F401  (populates Base.metadata)
from app.db.base import Base

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
